version: '3'
services:
  mongodb:
    image: 'mongo:latest'
  redis: 
    image: 'redis:latest'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - name=value
