name: deploy Karpah Client
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: build the stack
        run: docker build -t test -f ./frontend/Dockerfile.dev ./frontend
      - name: run the tests
        run: docker run -e CI=true test npm run test:unit
