name: deploy Karpah Client
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t julietkarpah/karpahclient -f ./frontend/Dockerfile.dev .
      - run: docker run -e CI=true julietkarpah/karpahclient npm run test:unit
       
